webapp:
  build: .
  command: bin/web
  environment:
    - RACK_ENV=development
  mem_limit: 100m
  labels:
    - convox.port.443.protocol=tls
  ports:
    - 80:3000
    - 443:3000
  links:
    - cache
  labels:
    - foobar.role=web
    - foobar.purpose=dev
    - convox.health.timeout=5
    - convox.deployment.minimum=50
    - convox.deployment.maximum=100
    - convox.health.path=/check
worker:
  build: .
  command: bin/worker
  mem_limit: 100m
  environment:
    - RACK_ENV=development
  links:
    - cache
  labels:
    - foobar.role=worker
    - foobar.purpose=dev
    - convox.deployment.minimum=100
cache:
  image: convox/redis
  ports:
    - 6379
