web:
  build: .
  command: bin/web
  environment:
    - RACK_ENV=development
  labels:
    - convox.port.443.protocol=tls
  ports:
    - 80:3000
    - 443:3000
  links:
    - redis
  labels:
    - foobar.role=web
    - foobar.purpose=dev
    - convox.health.timeout=5
    - convox.deployment.minimum=50
    - convox.deployment.maximum=100
    - convox.health.path=/check
worker:
  build: .
  command: bin/worker
  environment:
    - RACK_ENV=development
  links:
    - redis
  labels:
    - foobar.role=worker
    - foobar.purpose=dev
    - convox.deployment.minimum=100
# redis:
#   image: convox/redis
#   ports:
#     - 6379
#   labels:
#     - foobar.role=db
#     - foobar.purpose=dev
